# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount:
  api: 1

image: # must override
  repository: nginx
  tag: stable 
  pullPolicy: IfNotPresent

service:
  name: http
  type: ClusterIP
  externalPort: 80
  internalPort: 5000

flask:
  appConfiguration: config.ProductionConfig
  secret: N2NjYWY0ZDQ1NzEwNWNiNDU3MDgyYzdl

ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - job-offers-api.apps.abdelhalimresu.com
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

postgres:
  hostname: postgres
  user: api
  password: dF1nu8xT6jBz01iXAfYDCmGdQO1IOc4EOgqVB703
  database: joboffers
  volumeSize: 5Gi

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
