version: '3'

services:

  postgres:
    image: 'postgres:10.2'
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    ports:
      - '5432:5432'