version: '3'

services:

  api:
    build: .
    command: bash -c "python manage.py db upgrade && uwsgi --socket 0.0.0.0:5000 --protocol=http -w wsgi"
    volumes:
      - .:/src
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: 'postgres:10.2'
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - './data:/var/lib/postgresql/data/'