apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "chart.fullname" . }}
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount.api }}
  template:
    metadata:
      labels:
        app: {{ template "chart.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          command: ["/bin/bash", "-c"]
          args: ["uwsgi --socket 0.0.0.0:5000 --protocol=http -w wsgi"]
          env:
            - name: FLASK_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: flask_secret_key
            - name: APP_CONFIGURATION
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: app_configuration
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: postgres_pass
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: postgres_host
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: postgres_db
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
